<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlgoMiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlgoMiseRepository extends EntityRepository
{
    public function findByAlgoMise($utilisateur)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.utilisateur = :utilisateur')
            ->setParameter('utilisateur', $utilisateur)
            ->orderBy('a.id', 'DESC')
//            ->orderBy('s.end', 'ASC')
        ;

        ;
        return  $qb->getQuery()->getResult();
    }
}
