<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApiResultatTennisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiResultatTennisRepository extends EntityRepository
{
}
