<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CalculetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalculetteRepository extends EntityRepository
{
}
