<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClassementJoueursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassementJoueursRepository extends EntityRepository
{
        public function findByJoueur($idJoueur)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.idJoueur = :idJoueur')
            ->setParameter('idJoueur', $idJoueur)
            ->orderBy('c.semaine', 'ASC');

        ;
        return  $qb->getQuery()->getResult();
    }

    public function findByIdJoueur($idJoueur)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.idJoueur = :idJoueur')
            ->setParameter('idJoueur', $idJoueur)
            ->orderBy('c.semaine', 'DESC');

        ;
        return  $qb->getQuery()->getResult();
    }

    public function findByWeek($idJoueur, $week, $year)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.idJoueur = :idJoueur AND c.semaine >= :week AND c.annee = :year')
            ->setParameter('idJoueur', $idJoueur)
            ->setParameter('week', $week)
            ->setParameter('year', $year)
            ->orderBy('c.semaine', 'ASC');

        ;
        return  $qb->getQuery()->getResult();
    }

    public function findByWeekInf($idJoueur, $week, $year)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.idJoueur = :idJoueur AND c.semaine >= :week AND c.annee = :year')
            ->setParameter('idJoueur', $idJoueur)
            ->setParameter('week', $week)
            ->setParameter('year', $year)
            ->orderBy('c.semaine', 'ASC');

        ;
        return  $qb->getQuery()->getResult();
    }
}
