<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoteListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoteListRepository extends EntityRepository
{
}
