<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoteListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoteListRepository extends EntityRepository
{

    public function findByCoteListResult($data)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.cote = :cote')
            ->setParameter('cote', $data['cote']);
        if($data['sport']) {
            $qb->andWhere('c.sportId = :sport')
                ->setParameter('sport', $data['sport']);
        }
        if($data['typeResultat']) {
            $qb->andWhere('c.marketTypeId = :typeResultat')
                ->setParameter('typeResultat', $data['typeResultat']);
        }
//        if($data['typeResultMarketType']) {
//            $qb->andWhere('c.marketType = :marketType')
//                ->setParameter('marketType', $data['marketType']);
//        }


        ;
        return  $qb->getQuery()->getResult();
    }

    public function findByCoteListTennisCote($sportId, $marketTypeId, $statut)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.sportId = :sportId AND c.marketTypeId = :marketTypeId AND c.statut = :statut')
            ->setParameter('sportId', $sportId)
            ->setParameter('statut', $statut)
            ->setParameter('marketTypeId', $marketTypeId);


        ;
        return  $qb->getQuery()->getResult();
    }
}
