<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulesRepository extends EntityRepository
{
}
