<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JoueursTennisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueursTennisRepository extends EntityRepository
{

//    public function findByJoueur($nom)
//    {
//        $qb = $this->createQueryBuilder('j');
//        $qb->where('j.nom = :nom OR j.nomAdversaire = :nomAdversaire')
//            ->setParameter('nom', $nom)
//            ->setParameter('nomAdversaire', $nom);
//
//        ;
//        return  $qb->getQuery()->getResult();
//    }
}
