<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JoueurTennisScoreCoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurTennisScoreCoteRepository extends EntityRepository
{
    public function findByCote($minCote, $maxCote)
    {
        $qb = $this->createQueryBuilder('j');
        $qb->where('j.cote >= :minCote AND j.cote <= :maxCote')
            ->setParameter('minCote', $minCote)
            ->setParameter('maxCote', $maxCote)
//            ->orderBy('s.end', 'ASC')
        ;

        ;
        return  $qb->getQuery()->getResult();
    }
}
