<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JoueursTennisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueursTennisRepository extends EntityRepository
{
}
