<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JoueurTennisScoreCoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurTennisScoreCoteRepository extends EntityRepository
{
    public function findByCote($cote)
    {
        $qb = $this->createQueryBuilder('j');
        $qb->where('j.cote = :cote')
            ->setParameter('cote', $cote)
//            ->orderBy('s.end', 'ASC')
        ;

        ;
        return  $qb->getQuery()->getResult();
    }
}
