<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MatchFiniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchFiniRepository extends EntityRepository
{
    public function findByTennisResult($data)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.minCote BETWEEN :minCote AND :maxCote')
            ->setParameter('minCote', $data['coteMin'])
            ->setParameter('maxCote', $data['coteMax'])
            ->andWhere('m.nbSetGagnant = :nbSetGagnant')
            ->setParameter('nbSetGagnant', $data['nbSetGagnant']);
//        $qb->where('t.minCote <= :minCote')
//            ->setParameter('minCote', $data['cote'])
//            ->andWhere('t.nbSetGagnant = :nbSetGagnant')
//            ->setParameter('nbSetGagnant', $data['nbSetGagnant']);




        ;
        return $qb->getQuery()->getResult();
    }

    public function findByMatchFini()
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.matchFini = 1')
            ->andWhere('m.sportId = 1')
//        $qb->where('t.minCote <= :minCote')
//            ->setParameter('minCote', $data['cote'])
//            ->andWhere('t.nbSetGagnant = :nbSetGagnant')
//            ->setParameter('nbSetGagnant', $data['nbSetGagnant']);




        ;
        return $qb->getQuery()->getResult();
    }
}
