<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TableCorrespondanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableCorrespondanceRepository extends EntityRepository
{
}
