<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TennisScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TennisScoreRepository extends EntityRepository
{
    public function findByTennisResult($data)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->where('t.minCote BETWEEN :minCote AND :maxCote')
                ->setParameter('minCote', $data['coteMin'])
                ->setParameter('maxCote', $data['coteMax'])
            ->andWhere('t.nbSetGagnant = :nbSetGagnant')
            ->setParameter('nbSetGagnant', $data['nbSetGagnant']);
//        $qb->where('t.minCote <= :minCote')
//            ->setParameter('minCote', $data['cote'])
//            ->andWhere('t.nbSetGagnant = :nbSetGagnant')
//            ->setParameter('nbSetGagnant', $data['nbSetGagnant']);




        ;
        return $qb->getQuery()->getResult();
    }
}
