<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TennisCoteCumulRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TennisCoteCumulRepository extends EntityRepository
{
    public function findByTennisCumulCote($data, $marketTypeId)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where('(m.cote BETWEEN :minCote AND :maxCote) AND m.marketTypeId = :marketTypeId')
            ->setParameter('minCote', $data['coteMin'])
            ->setParameter('maxCote', $data['coteMax'])
            ->setParameter('marketTypeId', $marketTypeId)
//        $qb->where('t.minCote <= :minCote')
//            ->setParameter('minCote', $data['cote'])
//            ->andWhere('t.nbSetGagnant = :nbSetGagnant')
//            ->setParameter('nbSetGagnant', $data['nbSetGagnant']);
        ;
        return $qb->getQuery()->getResult();
    }

    public function findByCoteMarketTypeId($cote, $marketTypeId, $sport)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->where('t.cote = :cote AND t.marketTypeId = :marketTypeId AND t.sport = :sport')
            ->setParameter('cote', $cote)
            ->setParameter('sport', $sport)
            ->setParameter('marketTypeId', $marketTypeId)
            ->setMaxResults(1);
        ;
        return  $qb->getQuery()->getResult();
    }

}
