<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TennisCoteCumulRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TennisCoteCumulRepository extends EntityRepository
{
    public function findByTennisCumulCote($data)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.cote BETWEEN :minCote AND :maxCote')
            ->setParameter('minCote', $data['coteMin'])
            ->setParameter('maxCote', $data['coteMax'])
//        $qb->where('t.minCote <= :minCote')
//            ->setParameter('minCote', $data['cote'])
//            ->andWhere('t.nbSetGagnant = :nbSetGagnant')
//            ->setParameter('nbSetGagnant', $data['nbSetGagnant']);




        ;
        return $qb->getQuery()->getResult();
    }
}
