<?php

namespace FdjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TennisScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TennisScoreRepository extends EntityRepository
{
    public function findByTennisResult($data)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->where('t.minCote <= :minCote')
                ->setParameter('minCote', $data['cote'])
            ->andWhere('t.nbSetGagnant = :nbSetGagnant')
            ->setParameter('nbSetGagnant', $data['nbSetGagnant']);


        //        if($data['typeResultMarketType']) {
        //            $qb->andWhere('c.marketType = :marketType')
        //                ->setParameter('marketType', $data['marketType']);
        //        }


        ;
        return $qb->getQuery()->getResult();
    }
}
